name: stargan
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - absl-py=0.13.0=py37haa95532_0
  - aiohttp=3.7.4=py37h2bbff1b_1
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - astor=0.8.1=py37haa95532_0
  - async-timeout=3.0.1=py37haa95532_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py37haa95532_0
  - bottleneck=1.3.2=py37h2a96729_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2021.9.30=haa95532_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py37haa95532_0
  - cffi=1.14.6=py37h2bbff1b_0
  - chardet=3.0.4=py37haa95532_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.1=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py37h2bbff1b_2
  - cryptography=3.4.7=py37h71e12ea_0
  - cycler=0.10.0=py37_0
  - cython=0.29.24=py37hd77b12b_0
  - debugpy=1.4.1=py37hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.36.1=py37hc60d5dd_1
  - hdf5=1.8.20=hac2f561_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py37haa95532_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipykernel=6.4.1=py37haa95532_1
  - ipython=7.27.0=py37hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py37haa95532_1
  - jpeg=9d=h2bbff1b_0
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py37haa95532_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py37hd77b12b_0
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.17.2=h23ce68f_1
  - libtiff=4.2.0=hd0e1b90_0
  - lz4-c=1.9.3=h2bbff1b_1
  - markdown=3.3.4=py37haa95532_0
  - matplotlib=3.4.2=py37haa95532_0
  - matplotlib-base=3.4.2=py37h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.0=py37h277e83a_2
  - mkl_random=1.2.2=py37hf11a4ad_0
  - multidict=5.1.0=py37h2bbff1b_2
  - munkres=1.1.4=py_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numexpr=2.7.3=py37hb80d3ca_1
  - numpy=1.20.3=py37ha4e8547_0
  - numpy-base=1.20.3=py37hc2deb75_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h40b0b35_0
  - openssl=1.1.1l=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - pandas=1.3.3=py37h6214cd6_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py37h4fa10fc_0
  - pip=21.0.1=py37haa95532_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.17.2=py37hd77b12b_0
  - py-opencv=3.4.2=py37hc319ecb_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py37haa95532_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h6538335_2
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=228=py37hbaba5e8_1
  - pyzmq=22.2.1=py37hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - setuptools=58.0.4=py37haa95532_0
  - sip=4.19.8=py37h6538335_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.1.0=eigen_py37hd727fc0_0
  - tensorflow-base=2.1.0=eigen_py37h49b2757_0
  - termcolor=1.1.0=py37haa95532_1
  - tk=8.6.10=he774522_0
  - tornado=6.1=py37h2bbff1b_0
  - tqdm=4.62.2=pyhd3eb1b0_1
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=0.16.1=py_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37_0
  - wrapt=1.12.1=py37he774522_1
  - xz=5.2.5=h62dcd97_0
  - yarl=1.6.3=py37h2bbff1b_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - astunparse==1.6.3
    - filelock==3.0.12
    - gast==0.2.2
    - gdown==3.13.1
    - h5py==2.10.0
    - opencv-python==4.5.3.56
    - scipy==1.4.1
    - tensorboard==2.1.1
    - tensorflow-addons==0.9.1
    - tensorflow-estimator==2.1.0
    - typeguard==2.12.1
prefix: C:\tools\Anaconda3\envs\stargan
